project:
  type: website
  output-dir: docs
  resources:
    - files/**

website:
  title: "Wise Health HMR"
  favicon: files/images/favicon.png

  navbar:
    background: "#05336B"
    foreground: "#FFFFFF"
    logo: /files/images/wisehealthlogowhite.jpg
    href: index.qmd  
    left:
      - text: Sean Zhang
        href: index.qmd    
      - text: About
        href: about.qmd
      - text: Home Medicines Reviews
        href: hmr.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/sean-zhang-a4486a290/

  page-navigation: true
  page-footer: 
    center: "[Sean Zhang](http://wisehealthhmr.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: http://wisehealthhmr.com
  open-graph: true
  twitter-card: true 
  site-url: "http://wisehealthhmr.com"
  google-analytics:
    tracking-id: "G-TEC97F8RGK"
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
    include-in-header: files/includes/_msclarity.html
    title: false



