project:
  type: website
  output-dir: docs

website:
  title: "Sean Zhang"
  image: "/files/images/sean.png"
  description: "Accredited Pharmacist | Clinical Mentor | Aspiring Medical Science Liaison | Expert in HMR & Interprofessional Collaboration"
 
  navbar:
    background: "#05336B"
    foreground: "#FFFFFF"
    left:
      - text: About
        href: about.qmd
      - text: Teaching
        href: teaching.qmd
      - text: HMR
        href: hmr.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/sean-zhang-a4486a290/
  page-navigation: true
  page-footer: 
    left: "[Sean Zhang](http://wisehealthhmr.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: http://wisehealthhmr.com
#  repo-actions: [edit, issue, source]
  open-graph: true
  twitter-card: true 
#  card-style: summary      
  site-url: "http://wisehealthhmr.com"
  google-analytics:
    tracking-id: "G-TEC97F8RGK"
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true 



